name: Build Packages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install base-devel and dependencies
      run: |
        pacman -Sy --noconfirm archlinux-keyring
        pacman -Syu --noconfirm --needed base-devel git

    - name: Build all PKGBUILDs
      run: |
        set -e
        for d in */; do
          if [ -f "$d/PKGBUILD" ]; then
            echo "Building package in $d"
            cd "$d"
            makepkg -sf --noconfirm
            cd ..
          fi
        done

    - name: Upload built packages
      if: success() && always()  # only runs if previous steps succeeded
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: |
          **/*.pkg.tar.zst
          **/*.pkg.tar.xz
        if-no-files-found: error
